name: Build (Just for Test)

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'development/**'
      - 'dependabot/**'  
  push:
    branches: ["development/main"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run build
